#Examlple 4 - arguments
#Arguments are like varible - which can be overwritten during image build
ARG IMAGE_VERSION=latest

FROM ubuntu:${IMAGE_VERSION}
CMD ["/bin/echo" , "hello all lets learn some argumentss in docker image"]