#Base image
FROM ubuntu:latest
CMD ["/bin/echo" , "hello all" , "Welcome to multi cmd1"]  
CMD ["/bin/echo" , "hello all" , "Welcome to multi cmd2"]
CMD ["/bin/echo" , "hello all" , "Welcome to multi cmd3"]
CMD ["/bin/echo" , "hello all" , "Welcome to multi cmd4"]
CMD ["/bin/echo" , "hello all" , "Welcome to multi cmd5"]