#Base image
FROM ubuntu:latest

ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint1"]
ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint2"]
ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint3"]
ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint4"]
ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint5"]
ENTRYPOINT ["/bin/echo" , "Welcome to multi entrypoint6"]
CMD ["/bin/echo" , "hello cmd1"]